version: "2"
services:
  # START NZBGet
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /home/srv-user/htpc-config/nzbget/:/config
      - /home/srv-user/nzbget/downloads:/downloads
    network_mode: "host"
    restart: unless-stopped
  # END NZBGet
  # START TRANSMISSION
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /home/srv-user/htpc-config/transmission/:/config
      - /home/srv-user/transmission/downloads/:/downloads
      - /home/srv-user/transmission/watch:/watch
    network_mode: "host"
    restart: unless-stopped
  # END TRANSMISSION
  # START PIHOLE
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Zurich'
      WEBPASSWORD: 'pihole-0'
      DNS1: '8.8.8.8'
      DNS2: '8.8.4.4'
      ServerIP: '192.168.86.143'
    volumes:
       - '/home/srv-user/htpc-config/pihole/etc-pihole/:/etc/pihole/'
       - '/home/srv-user/htpc-config/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    network_mode: "host"
    restart: unless-stopped
  # END PIHOLE
  # START SONARR
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /home/srv-user/htpc-config/sonarr/:/config
      - /home/srv-user/media/tv/:/tv
      - /home/srv-user/nzbget/downloads/:/downloads
    network_mode: "host"
    restart: unless-stopped
  # END SONARR
  # START RADARR
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /home/srv-user/htpc-config/radarr/:/config
      - /home/srv-user/media/movies/:/movies
      - /home/srv-user/nzbget/downloads/:/downloads
    network_mode: "host"
    restart: unless-stopped
  # END RADARR
  # START LIDARR
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /home/srv-user/htpc-config/lidarr/:/config
      - /home/srv-user/media/music/:/music
      - /home/srv-user/nzbget/downloads/:/downloads
    network_mode: "host"
    restart: unless-stopped
  # END LIDARR
